/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import dao.BalikDao;
import entity.Balik;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author cemr_
 */
public class BalikEkrani extends javax.swing.JDialog {

    DefaultTableModel model;

    BalikDao balikDao = new BalikDao();

    /**
     * Creates new form BalikEkrani
     */
    public BalikEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) balik_table.getModel();
        balikGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        balik_table = new javax.swing.JTable();
        arama_alani = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        balik_cinsi_alani = new javax.swing.JTextField();
        fiyat_alani = new javax.swing.JTextField();
        kilo_alani = new javax.swing.JTextField();
        boy_alani = new javax.swing.JTextField();
        yem_kategori_alani = new javax.swing.JTextField();
        yem_kilo_alani = new javax.swing.JTextField();
        tarih_alani = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        ekle_button = new javax.swing.JButton();
        guncelle_button = new javax.swing.JButton();
        sil_button = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));

        balik_table.setBackground(new java.awt.Color(255, 51, 255));
        balik_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "balik_cinsi", "balik_fiyat", "kilo", "boy", "yem_kategori", "yem_kilo", "getirilis_tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        balik_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                balik_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(balik_table);
        if (balik_table.getColumnModel().getColumnCount() > 0) {
            balik_table.getColumnModel().getColumn(0).setResizable(false);
            balik_table.getColumnModel().getColumn(1).setResizable(false);
            balik_table.getColumnModel().getColumn(2).setResizable(false);
            balik_table.getColumnModel().getColumn(3).setResizable(false);
            balik_table.getColumnModel().getColumn(4).setResizable(false);
            balik_table.getColumnModel().getColumn(5).setResizable(false);
            balik_table.getColumnModel().getColumn(6).setResizable(false);
            balik_table.getColumnModel().getColumn(7).setResizable(false);
        }

        arama_alani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_alaniKeyReleased(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(153, 153, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel1.setText("Ara : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Balik Cins :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("Balik Fiyat : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setText("Kilo :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel5.setText("Boy :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel6.setText("Yem Kategori : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel7.setText("Yem Kilo : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel8.setText("Getirilme Tarih : ");

        balik_cinsi_alani.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        mesaj_yazisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        ekle_button.setBackground(new java.awt.Color(51, 255, 102));
        ekle_button.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ekle_button.setText("Balik Ekle");
        ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_buttonActionPerformed(evt);
            }
        });

        guncelle_button.setBackground(new java.awt.Color(51, 255, 51));
        guncelle_button.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        guncelle_button.setText("Balik Guncelle");
        guncelle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_buttonActionPerformed(evt);
            }
        });

        sil_button.setBackground(new java.awt.Color(51, 255, 51));
        sil_button.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        sil_button.setText("Balik Sil");
        sil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_buttonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel9.setText("Balik Ekrani");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 825, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(yem_kilo_alani, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yem_kategori_alani, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boy_alani, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arama_alani, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                    .addComponent(balik_cinsi_alani, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fiyat_alani, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kilo_alani, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tarih_alani))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(guncelle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sil_button, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 184, Short.MAX_VALUE))
                            .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(arama_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(balik_cinsi_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle_button))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fiyat_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kilo_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle_button))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boy_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(yem_kategori_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil_button))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(yem_kilo_alani, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(tarih_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void bosalt() {
        balik_cinsi_alani.setText("");
        fiyat_alani.setText("");
        kilo_alani.setText("");
        boy_alani.setText("");
        yem_kategori_alani.setText("");
        yem_kilo_alani.setText("");
        tarih_alani.setText("");
    }
    private void balik_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_balik_tableMouseClicked
        // TODO add your handling code here:
        int selectedRow = balik_table.getSelectedRow();

        balik_cinsi_alani.setText(model.getValueAt(selectedRow, 1).toString());
        fiyat_alani.setText(model.getValueAt(selectedRow, 2).toString());
        kilo_alani.setText(model.getValueAt(selectedRow, 3).toString());
        boy_alani.setText(model.getValueAt(selectedRow, 4).toString());
        yem_kategori_alani.setText(model.getValueAt(selectedRow, 5).toString());
        yem_kilo_alani.setText(model.getValueAt(selectedRow, 6).toString());
        tarih_alani.setText(model.getValueAt(selectedRow, 7).toString());
    }//GEN-LAST:event_balik_tableMouseClicked

    public void dinamikAra(String ara) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        balik_table.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void arama_alaniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_alaniKeyReleased
        // TODO add your handling code here:

        String ara = arama_alani.getText();

        dinamikAra(ara);
    }//GEN-LAST:event_arama_alaniKeyReleased

    private void ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_buttonActionPerformed
        // TODO add your handling code here:

        mesaj_yazisi.setText("");

        String cins = balik_cinsi_alani.getText();
        String fiyat = fiyat_alani.getText();
        String kilo = kilo_alani.getText();
        String boy = boy_alani.getText();
        String kategori = yem_kategori_alani.getText();
        String yem_kilo = yem_kilo_alani.getText();
        String tarih = tarih_alani.getText();
        
        boolean kontrol = balikDao.kontrolYap(cins,kilo,boy,tarih);

        if (cins.equals("") && fiyat.equals("") && kilo.equals("") && boy.equals("")
                && kategori.equals("") && yem_kilo.equals("") && tarih.equals("")) {

            JOptionPane.showMessageDialog(this, "Lutfen gerekli alanları doldurunuz.");
        } else if (!kontrol) {
            JOptionPane.showMessageDialog(this, "Böyle bir kayıt zaten var.");
        }
        
        else {
            balikDao.ekleBalik(cins, fiyat, kilo, boy, kategori, yem_kilo, tarih);
            mesaj_yazisi.setText("Balık basarıyla eklendi");

        }

        balikGoruntule();
        bosalt();

    }//GEN-LAST:event_ekle_buttonActionPerformed

    private void guncelle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_buttonActionPerformed
        // TODO add your handling code here:

        mesaj_yazisi.setText("");

        String cins = balik_cinsi_alani.getText();
        String fiyat = fiyat_alani.getText();
        String kilo = kilo_alani.getText();
        String boy = boy_alani.getText();
        String kategori = yem_kategori_alani.getText();
        String yem_kilo = yem_kilo_alani.getText();
        String tarih = tarih_alani.getText();

        int selectedRow = balik_table.getSelectedRow();

        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("balık tablosu suanda bos");
            } else {
                mesaj_yazisi.setText("lutfen guncellenecek bir balık seçiniz?");
            }

        } else {
            long id = (long) model.getValueAt(selectedRow, 0);
            if (true) {
                balikDao.guncelleBalik(id, cins, fiyat, kilo, boy, kategori, yem_kilo, tarih);
                mesaj_yazisi.setText("Balık basarıyla guncellendi");
            } else {
                mesaj_yazisi.setText("balık guncellenirken bir hata olustu ...lütfen tekrar deneyin..");
            }

            balikGoruntule();
            bosalt();
        }


    }//GEN-LAST:event_guncelle_buttonActionPerformed

    private void sil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_buttonActionPerformed
        // TODO add your handling code here:

        int selectedRow = balik_table.getSelectedRow();

        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("balık tablosu suanda bos");
            } else {
                mesaj_yazisi.setText("lutfen silinecek bir balık seçiniz?");
            }

        } else {
            long id = (long) model.getValueAt(selectedRow, 0);
            if (true) {
                balikDao.silBalik(id);
                mesaj_yazisi.setText("Balık basarıyla silindi");
            } else {
                mesaj_yazisi.setText("balık silinirken bir hata olustu ...lütfen tekrar deneyin..");
            }

        }
        balikGoruntule();
        bosalt();
    }//GEN-LAST:event_sil_buttonActionPerformed
    ///////////////Jframe Geciş methodu/////////////////////////////

    public void close() {
        WindowEvent windowEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowEvent);
    }

    public void open() {
        WindowEvent windowEvent = new WindowEvent(this, WindowEvent.WINDOW_OPENED);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowEvent);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BalikEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BalikEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BalikEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BalikEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                BalikEkrani dialog = new BalikEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
//////////////////listeleme////////////////////

    public void balikGoruntule() {
        model.setRowCount(0);//tabloyu sıfırlamak için

        ArrayList<Balik> balik = new ArrayList<>();

        balik = balikDao.balikList();

        if (balik != null) {
            for (Balik balik1 : balik) {
                Object[] eklenecek = {
                    balik1.getId(), balik1.getBalikCinsi(), balik1.getBalikFiyat(), balik1.getKilo(), balik1.getBoy(),
                    balik1.getYemKategori(), balik1.getYemKilo(), balik1.getGetirilisTarihi()
                };

                model.addRow(eklenecek);
            }
        } else {
            System.out.print("hata");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_alani;
    private javax.swing.JTextField balik_cinsi_alani;
    private javax.swing.JTable balik_table;
    private javax.swing.JTextField boy_alani;
    private javax.swing.JButton ekle_button;
    private javax.swing.JTextField fiyat_alani;
    private javax.swing.JButton guncelle_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kilo_alani;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton sil_button;
    private javax.swing.JTextField tarih_alani;
    private javax.swing.JTextField yem_kategori_alani;
    private javax.swing.JTextField yem_kilo_alani;
    // End of variables declaration//GEN-END:variables

}
