/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;

/**
 *
 * @author cemr_
 */
public class TableEkrani extends javax.swing.JFrame {

    /**
     * Creates new form TableEkrani
     */
    public TableEkrani() {
        initComponents();
    }

    public void close() {
        WindowEvent windowEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(windowEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        balik_button = new javax.swing.JButton();
        depo_button = new javax.swing.JButton();
        havuz_button = new javax.swing.JButton();
        cikis_button = new javax.swing.JButton();
        user_button = new javax.swing.JButton();
        yem_buttton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Tablolar");

        balik_button.setBackground(new java.awt.Color(51, 255, 51));
        balik_button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        balik_button.setText("Balık Ekranı");
        balik_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balik_buttonActionPerformed(evt);
            }
        });

        depo_button.setBackground(new java.awt.Color(51, 255, 51));
        depo_button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        depo_button.setText("Depo Ekranı");
        depo_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depo_buttonActionPerformed(evt);
            }
        });

        havuz_button.setBackground(new java.awt.Color(51, 255, 51));
        havuz_button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        havuz_button.setText("Havuz Ekranı");
        havuz_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                havuz_buttonActionPerformed(evt);
            }
        });

        cikis_button.setBackground(new java.awt.Color(255, 0, 51));
        cikis_button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        cikis_button.setText("Cıkıs yap");
        cikis_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cikis_buttonActionPerformed(evt);
            }
        });

        user_button.setBackground(new java.awt.Color(51, 255, 51));
        user_button.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        user_button.setText("User Ekranı");
        user_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_buttonActionPerformed(evt);
            }
        });

        yem_buttton.setBackground(new java.awt.Color(51, 255, 51));
        yem_buttton.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        yem_buttton.setText("Yem Ekranı");
        yem_buttton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yem_butttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(balik_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(yem_buttton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(depo_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cikis_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(havuz_button, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(havuz_button))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(depo_button)
                            .addComponent(balik_button))))
                .addGap(195, 195, 195)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(user_button)
                    .addComponent(yem_buttton)
                    .addComponent(cikis_button))
                .addContainerGap(261, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_buttonActionPerformed
        // TODO add your handling code here:
        UserEkrani userEkrani = new UserEkrani(this, true);
        //setVisible(false);
        userEkrani.setVisible(true);
       // System.exit(0);
    }//GEN-LAST:event_user_buttonActionPerformed

    private void balik_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balik_buttonActionPerformed
        // TODO add your handling code here:

        BalikEkrani balikEkrani = new BalikEkrani(this, true);
       // setVisible(false);
        balikEkrani.setVisible(true);
       // System.exit(0);
      
         
    }//GEN-LAST:event_balik_buttonActionPerformed

    private void depo_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depo_buttonActionPerformed
        // TODO add your handling code here:
        DepoEkrani depoEkrani = new DepoEkrani(this, true);
        //setVisible(false);
        depoEkrani.setVisible(true);

    }//GEN-LAST:event_depo_buttonActionPerformed

    private void havuz_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_havuz_buttonActionPerformed
        // TODO add your handling code here:
        HavuzEkrani havuzEkrani = new HavuzEkrani(this, true);
       // setVisible(false);
        havuzEkrani.setVisible(true);
        //System.exit(0);
    }//GEN-LAST:event_havuz_buttonActionPerformed

    private void yem_butttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yem_butttonActionPerformed
        // TODO add your handling code here:
        YemEkrani yemEkrani = new YemEkrani(this, true);
       // setVisible(false);
        yemEkrani.setVisible(true);
       // System.exit(0);
    }//GEN-LAST:event_yem_butttonActionPerformed

    private void cikis_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cikis_buttonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cikis_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableEkrani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton balik_button;
    private javax.swing.JButton cikis_button;
    private javax.swing.JButton depo_button;
    private javax.swing.JButton havuz_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton user_button;
    private javax.swing.JButton yem_buttton;
    // End of variables declaration//GEN-END:variables

}
