/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import dao.UserDao;
import entity.User;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author cemr_
 */
public class UserEkrani extends javax.swing.JDialog {
    
    DefaultTableModel model;
    
    private UserDao userDao;
    
    public UserDao getUserDao() {
        if (this.userDao == null) {
            this.userDao = new UserDao();
        }
        return userDao;
    }
    
    public void setUserDao(UserDao userDao) {
        this.userDao = userDao;
    }

    /**
     * Creates new form UserEkrani
     */
    public UserEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) table_alani.getModel();
        userGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_alani = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mesaj_yazisi = new javax.swing.JLabel();
        kullanici_alani = new javax.swing.JTextField();
        parola_alani = new javax.swing.JPasswordField();
        ekle_button = new javax.swing.JButton();
        guncelle_button = new javax.swing.JButton();
        sil_button = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        arama_alani = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        table_alani.setBackground(new java.awt.Color(255, 51, 255));
        table_alani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Kullanıcı Adı", "Parola"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_alani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_alaniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_alani);
        if (table_alani.getColumnModel().getColumnCount() > 0) {
            table_alani.getColumnModel().getColumn(0).setResizable(false);
            table_alani.getColumnModel().getColumn(1).setResizable(false);
            table_alani.getColumnModel().getColumn(2).setResizable(false);
        }

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel1.setText("Kullanıcı Adınız : ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Parola : ");

        mesaj_yazisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));

        ekle_button.setBackground(new java.awt.Color(51, 255, 51));
        ekle_button.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ekle_button.setText("Yeni Kullanıcı Ekle");
        ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_buttonActionPerformed(evt);
            }
        });

        guncelle_button.setBackground(new java.awt.Color(102, 255, 51));
        guncelle_button.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        guncelle_button.setText("Kullanıcı Guncelle");
        guncelle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_buttonActionPerformed(evt);
            }
        });

        sil_button.setBackground(new java.awt.Color(102, 255, 51));
        sil_button.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        sil_button.setText("Kullanıcı Sil");
        sil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_buttonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Ara : ");

        arama_alani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_alaniKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel8.setText("User Ekrani");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arama_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE))
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kullanici_alani)
                            .addComponent(parola_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sil_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(guncelle_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ekle_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arama_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kullanici_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle_button))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(parola_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle_button))
                .addGap(40, 40, 40)
                .addComponent(sil_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean kontrol() {
        model.setRowCount(1);
        
        return true;
    }

    public void bosalt() {
        kullanici_alani.setText("");
        parola_alani.setText("");
    }
    
    private void table_alaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_alaniMouseClicked
        // TODO add your handling code here:
        int selectedRow = table_alani.getSelectedRow();
        
        kullanici_alani.setText(model.getValueAt(selectedRow, 1).toString());
        parola_alani.setText(model.getValueAt(selectedRow, 2).toString());
    }//GEN-LAST:event_table_alaniMouseClicked
    public void dinamikAra(String ara) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        table_alani.setRowSorter(tr);
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void arama_alaniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_alaniKeyReleased
        // TODO add your handling code here:
        String ara = arama_alani.getText();
        
        dinamikAra(ara);
    }//GEN-LAST:event_arama_alaniKeyReleased

    private void ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_buttonActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        
        String kullanici = kullanici_alani.getText();
        String parola = new String(parola_alani.getPassword());
        
        boolean kontrol = userDao.kontrolYap(kullanici, parola);
        
        if (kullanici.equals("") && parola.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen gerekli alanları doldurunuz ...");
        } else if (!kontrol) {
            JOptionPane.showMessageDialog(this, "Boyle bir kullanıcı zaten var...lutfen baska kullanıcı seciniz..");
        }
        
        else {
            this.getUserDao().ekleUser(kullanici, parola);
            mesaj_yazisi.setText("User basarıyla eklendi");
            //mesaj_yazisi.setText("User eklenirken bir hata olustu ...lütfen tekrar deneyin..");
        }
        
        userGoruntule();
        bosalt();
    }//GEN-LAST:event_ekle_buttonActionPerformed

    private void guncelle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_buttonActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        
        String kullanici = kullanici_alani.getText();
        String parola = new String(parola_alani.getPassword());
        
        int selectedRow = table_alani.getSelectedRow();
        
        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("User tablosu suanda bos");
            } else {
                mesaj_yazisi.setText("lutfen guncellenecek bir User seçiniz...");
            }
        } else {
            long id = (long) model.getValueAt(selectedRow, 0);
            this.getUserDao().guncelleUser(id, kullanici, parola);
            
            userGoruntule();
            
            mesaj_yazisi.setText("User basarıyla guncellendi");
            bosalt();
        }
    }//GEN-LAST:event_guncelle_buttonActionPerformed

    private void sil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_buttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_alani.getSelectedRow();
        
        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("User tablosu suanda bos");
            } else {
                mesaj_yazisi.setText("lutfen silinecek bir User seçiniz?");
            }
            
        } else {
            long id = (long) model.getValueAt(selectedRow, 0);
            if (true) {
                this.getUserDao().silUser(id);
                mesaj_yazisi.setText("User basarıyla silindi");
            } else {
                mesaj_yazisi.setText("User silinirken bir hata olustu ...lütfen tekrar deneyin..");
            }
            
        }        
        userGoruntule();
        bosalt();
    }//GEN-LAST:event_sil_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UserEkrani dialog = new UserEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_alani;
    private javax.swing.JButton ekle_button;
    private javax.swing.JButton guncelle_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kullanici_alani;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JPasswordField parola_alani;
    private javax.swing.JButton sil_button;
    private javax.swing.JTable table_alani;
    // End of variables declaration//GEN-END:variables

    private void userGoruntule() {
        model.setRowCount(0);
        
        ArrayList<User> users = new ArrayList<>();
        
        users = this.getUserDao().userList();
        
        if (users != null) {
            for (User user : users) {
                Object[] eklenecek = {
                    user.getId(), user.getUserName(), user.getPassword()
                };
                model.addRow(eklenecek);
            }
        } else {
            mesaj_yazisi.setText("tablo goruntulenemiyor");
        }
    }
}
