/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import dao.YemDao;
import entity.Yem;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author cemr_
 */
public class YemEkrani extends javax.swing.JDialog {

    DefaultTableModel model;

    YemDao yemDao = new YemDao();

    /**
     * Creates new form YemEkrani
     */
    public YemEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        /////benim yazdıgım metodlar/////////////////////////
        model = (DefaultTableModel) table_alani.getModel();
        yemGoruntule();
    }

    private void yemGoruntule() {
        model.setRowCount(0);

        ArrayList<Yem> yems = new ArrayList<>();

        yems = yemDao.yemListeleme();

        if (yems != null) {
            for (Yem yem : yems) {
                Object[] eklenecek = {
                    yem.getId(), yem.getYemKategori(), yem.getYemFiyat(), yem.getYemAdet(), yem.getYemMiktar(), yem.getGelmeTarihi()
                };

                model.addRow(eklenecek);
            }
        } else {
            System.out.println("hata");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_alani = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kategori_alani = new javax.swing.JTextField();
        fiyat_alani = new javax.swing.JTextField();
        yem_adet_alani = new javax.swing.JTextField();
        yem_miktar_alani = new javax.swing.JTextField();
        tarih_alani = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        arama_alani = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        ekle_button = new javax.swing.JButton();
        guncelle_button = new javax.swing.JButton();
        sil_button = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        table_alani.setBackground(new java.awt.Color(255, 0, 255));
        table_alani.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "yem_kategori", "yem_fiyat", "yem_adet", "yem_miktar", "gelme_tarihi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_alani.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_alaniMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_alani);
        if (table_alani.getColumnModel().getColumnCount() > 0) {
            table_alani.getColumnModel().getColumn(0).setResizable(false);
            table_alani.getColumnModel().getColumn(1).setResizable(false);
            table_alani.getColumnModel().getColumn(2).setResizable(false);
            table_alani.getColumnModel().getColumn(3).setResizable(false);
            table_alani.getColumnModel().getColumn(4).setResizable(false);
            table_alani.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setText("Yem Kategori(milim) :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setText("Yem Fiyat(TL) : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel4.setText("Yem Adet(sayi) : ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel5.setText("Yem Miktar(kg)");

        jLabel6.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel6.setText("Gelme Tarihi : ");

        yem_miktar_alani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yem_miktar_alaniActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("Ara :");

        arama_alani.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_alaniKeyReleased(evt);
            }
        });

        mesaj_yazisi.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mesaj_yazisi.setForeground(new java.awt.Color(255, 51, 51));

        ekle_button.setBackground(new java.awt.Color(102, 255, 51));
        ekle_button.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ekle_button.setText("Yem Ekle");
        ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_buttonActionPerformed(evt);
            }
        });

        guncelle_button.setBackground(new java.awt.Color(102, 255, 51));
        guncelle_button.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        guncelle_button.setText("Yem Guncelle");
        guncelle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_buttonActionPerformed(evt);
            }
        });

        sil_button.setBackground(new java.awt.Color(102, 255, 0));
        sil_button.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        sil_button.setText("Yem Sil");
        sil_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_buttonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel8.setText("Yem Ekrani");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(arama_alani))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tarih_alani, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(yem_miktar_alani)
                            .addComponent(yem_adet_alani)
                            .addComponent(fiyat_alani)
                            .addComponent(kategori_alani))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(guncelle_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sil_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(arama_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kategori_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle_button))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fiyat_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yem_adet_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guncelle_button))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yem_miktar_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tarih_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil_button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void yem_miktar_alaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yem_miktar_alaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yem_miktar_alaniActionPerformed
    public void bosalt(){
        kategori_alani.setText("");
        fiyat_alani.setText("");
        yem_adet_alani.setText("");
        yem_miktar_alani.setText("");
        tarih_alani.setText("");
    }
    private void table_alaniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_alaniMouseClicked
        // TODO add your handling code here:
        int selectedRow = table_alani.getSelectedRow();

        kategori_alani.setText(model.getValueAt(selectedRow, 1).toString());
        fiyat_alani.setText(model.getValueAt(selectedRow, 2).toString());
        yem_adet_alani.setText(model.getValueAt(selectedRow, 3).toString());
        yem_miktar_alani.setText(model.getValueAt(selectedRow, 4).toString());
        tarih_alani.setText(model.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_table_alaniMouseClicked
    public void dinamikAra(String ara) {
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        table_alani.setRowSorter(sorter);

        sorter.setRowFilter(RowFilter.regexFilter(ara));
    }
    private void arama_alaniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_alaniKeyReleased
        // TODO add your handling code here:
        String ara = arama_alani.getText();

        dinamikAra(ara);
    }//GEN-LAST:event_arama_alaniKeyReleased

    private void ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_buttonActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");

        String kategori = kategori_alani.getText();
        String fiyat = fiyat_alani.getText();
        String adet = yem_adet_alani.getText();
        String miktar = yem_miktar_alani.getText();
        String tarih = tarih_alani.getText();
        
         boolean kontrol = yemDao.kontrolYap(kategori,fiyat,adet,miktar,tarih);

        if (kategori.equals("") || fiyat.equals("") || adet.equals("") || miktar.equals("") || tarih.equals("")) {
            JOptionPane.showMessageDialog(this, "Lutfen gerekli alanları doldurunuz ...");
            
            return;
        } else if (!kontrol) {
            JOptionPane.showMessageDialog(this, "Boyle bir kayıt zaten var ...");
            return;
        }
        else {
            yemDao.ekleYem(kategori, fiyat, adet, miktar, tarih);
            mesaj_yazisi.setText("Yem basarıyla eklendi");
            // mesaj_yazisi.setText("Yem eklenirken bir hata olustu ...lütfen tekrar deneyin..");
        }

        yemGoruntule();
        bosalt();


    }//GEN-LAST:event_ekle_buttonActionPerformed

    private void guncelle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_buttonActionPerformed
        // TODO add your handling code here:
        mesaj_yazisi.setText("");
        String kategori = kategori_alani.getText();
        String fiyat = fiyat_alani.getText();
        String adet = yem_adet_alani.getText();
        String miktar = yem_miktar_alani.getText();
        String tarih = tarih_alani.getText();

        int selectedRow = table_alani.getSelectedRow();

        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("yem tablosu suanda bos");
            } else {
                mesaj_yazisi.setText("lutfen guncellenecek bir yem seçiniz...");
            }
        } else {
            long id = (long) model.getValueAt(selectedRow, 0);
            yemDao.guncelleYem(id, kategori, fiyat, adet, miktar, tarih);
            yemGoruntule();

            mesaj_yazisi.setText("yem basarıyla guncellendi");
            bosalt();
        }
    }//GEN-LAST:event_guncelle_buttonActionPerformed

    private void sil_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_buttonActionPerformed
        // TODO add your handling code here:
        int selectedRow = table_alani.getSelectedRow();

        if (selectedRow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("yem tablosu suanda bos");
            } else {
                mesaj_yazisi.setText("lutfen silinecek bir yem seçiniz?");
            }

        } else {
            long id = (long) model.getValueAt(selectedRow, 0);
            if (true) {
                try {
                    yemDao.silYem(id);
                } catch (SQLException ex) {
                    Logger.getLogger(YemEkrani.class.getName()).log(Level.SEVERE, null, ex);
                }
                mesaj_yazisi.setText("Yem basarıyla silindi");
            } else {
                mesaj_yazisi.setText("Yem silinirken bir hata olustu ...lütfen tekrar deneyin..");
            }

        }
        yemGoruntule();
        bosalt();
    }//GEN-LAST:event_sil_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YemEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YemEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YemEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YemEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                YemEkrani dialog = new YemEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama_alani;
    private javax.swing.JButton ekle_button;
    private javax.swing.JTextField fiyat_alani;
    private javax.swing.JButton guncelle_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kategori_alani;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JButton sil_button;
    private javax.swing.JTable table_alani;
    private javax.swing.JTextField tarih_alani;
    private javax.swing.JTextField yem_adet_alani;
    private javax.swing.JTextField yem_miktar_alani;
    // End of variables declaration//GEN-END:variables

}
